Mettal/Models/ViewModels/HtmlEditorViewModel.cs
namespace Mettal.Models.ViewModels
{
    public class HtmlEditorViewModel
    {
        public string PropertyName { get; set; }
        public string HtmlContent { get; set; }
    }
}

Mettal/Controllers/GostController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Mettal.Models.Entities;
using Mettal.Models.ViewModels;

namespace Mettal.Controllers
{
    [Authorize(Roles = "admin")]
    public class GostController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var vm = new GostView
            {
                Gosts = GetViewModelCollection<Gost, GostViewModel>().ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(GostViewModel vm)
        {
            if (ModelState.IsValid)
            {
                CreateModel<Gost, GostViewModel>(vm);
            }
            var items = GetViewModelCollection<Gost, GostViewModel>().ToList();
            return PartialView("_GostList", items);
        }

        [HttpPut]
        public ActionResult Update(List<GostViewModel> vm)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_GostList", vm);
            }

            foreach (var item in vm)
            {
                UpdateModel<Gost, GostViewModel>(item, item.Id);
            }

            var items = GetViewModelCollection<Gost, GostViewModel>().ToList();

            return PartialView("_GostList", items);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            DeleteModel<Gost>(id);

            var items = GetViewModelCollection<Gost, GostViewModel>().ToList();

            return PartialView("_GostList", items);
        }
    }
}

Mettal/Controllers/ManualController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Mettal.Models.Entities;
using Mettal.Models.ViewModels;

namespace Mettal.Controllers
{
    [Authorize(Roles = "admin")]
    public class ManualController : BaseController
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index()
        {
            ManualView vm = GetView();

            return View(vm);
        }

        [HttpGet]
        public ActionResult Categories()
        {
            ManualView vm = GetView();

            return View(vm);
        }

        [HttpPost]
        public ActionResult CreateCategory(ManualCategoryViewModel vm)
        {
            if (ModelState.IsValid)
            {
                ManualCategory category = new ManualCategory
                {
                    Name = vm.Name
                };
                DataContext.GetRepository<ManualCategory>().Create(category);
                DataContext.Save();
            }
            var items = GetCategoryViewModels();
            return PartialView("_ManualCategoryList", items);
        }

        [HttpPut]
        public ActionResult UpdateCategory(List<ManualCategoryViewModel> vm)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_ManualCategoryList", vm);
            }

            var repo = DataContext.GetRepository<ManualCategory>();

            if (repo != null)
            {
                foreach (var item in vm)
                {
                    ManualCategory category = repo.GetById(item.Id);

                    if (category != null)
                    {
                        category.Name = item.Name;
                        repo.Update(category);
                    }
                }

                DataContext.Save();
            }

            var items = GetCategoryViewModels();

            return PartialView("_ManualCategoryList", items);
        }

        [HttpDelete]
        public ActionResult DeleteCategory(int id)
        {
            DeleteModel<ManualCategory>(id);

            var items = GetCategoryViewModels();

            return PartialView("_ManualCategoryList", items);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var manual = GetViewModel<Manual, ManualViewModel>(id);

            if (manual == null)
            {
                return RedirectToAction("Index");
            }

            return View(manual);
        }

        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Categories");
            }

            var category = DataContext.GetRepository<ManualCategory>().GetById(id);

            if (category == null)
            {
                return RedirectToAction("Categories");
            }

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ManualViewModel vm, int id)
        {
            var category = DataContext.GetRepository<ManualCategory>().GetById(id);

            if (category == null)
            {
                return RedirectToAction("Categories");
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            Manual manual = new Manual
            {
                Name = vm.Name,
                HtmlContent = vm.HtmlContent,
                Category = category,
                IsDeleted = false
            };

            DataContext.GetRepository<Manual>().Create(manual);
            DataContext.Save();

            return RedirectToAction("Details", new { manual.Id });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var manual = GetViewModel<Manual, ManualViewModel>(id);

            if (manual == null)
            {
                return RedirectToAction("Index");
            }

            return View(manual);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ManualViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            Manual manual = DataContext.GetRepository<Manual>().GetById(vm.Id);

            if (manual == null)
            {
                return RedirectToAction("Categories");
            }

            manual.Name = vm.Name;
            manual.HtmlContent = vm.HtmlContent;

            DataContext.GetRepository<Manual>().Update(manual);
            DataContext.Save();

            return RedirectToAction("Details", new { id = vm.Id });
        }

        public ActionResult Delete(int id)
        {
            DeleteModel<Manual>(id);

            return RedirectToAction("Index");
        }

        protected ManualView GetView()
        {
            ManualView view = new ManualView
            {
                Settings = Settings,
                Categories = GetCategoryViewModels()
            };

            return view;
        }
        protected List<ManualCategoryViewModel> GetCategoryViewModels()
        {
            var result = new List<ManualCategoryViewModel>();
            var items = DataContext.GetRepository<ManualCategory>().GetAll().ToList();

            foreach (ManualCategory category in items)
            {
                var vmCategory = new ManualCategoryViewModel
                {
                    Id = category.Id,
                    Name = category.Name
                };
                foreach (Manual manual in category.Manuals.Where(i => !i.IsDeleted))
                {
                    var vmManual = new ManualViewModel
                    {
                        Id = manual.Id,
                        Name = manual.Name,
                        HtmlContent = manual.HtmlContent
                    };
                    vmCategory.Manuals.Add(vmManual);
                }
                result.Add(vmCategory);
            }

            return result;
        }
    }
}

Mettal/Controllers/MarkController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Mettal.Models.Entities;
using Mettal.Models.ViewModels;

namespace Mettal.Controllers
{
    [Authorize(Roles = "admin")]
    public class MarkController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var vm = new MarkView
            {
                Marks = GetViewModelCollection<Mark, MarkViewModel>().ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(MarkViewModel vm)
        {
            if (ModelState.IsValid)
            {
                CreateModel<Mark, MarkViewModel>(vm);
            }
            var items = GetViewModelCollection<Mark, MarkViewModel>().ToList();
            return PartialView("_MarkList", items);
        }

        [HttpPut]
        public ActionResult Update(List<MarkViewModel> vm)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_MarkList", vm);
            }

            foreach (var item in vm)
            {
                UpdateModel<Mark, MarkViewModel>(item, item.Id);
            }

            var items = GetViewModelCollection<Mark, MarkViewModel>().ToList();

            return PartialView("_MarkList", items);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            DeleteModel<Mark>(id);

            var items = GetViewModelCollection<Mark, MarkViewModel>().ToList();

            return PartialView("_MarkList", items);
        }
    }
}

Mettal/Controllers/SliderController.cs
using Mettal.Models.Entities;
using Mettal.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mettal.Controllers
{
    [Authorize(Roles = "admin")]
    public class SliderController : BaseController
    {
        public ActionResult Index()
        {
            var slides = GetSlideViewModels();
            return View(slides);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new SlideViewModel());
        }
        [HttpPost]
        public ActionResult Create(SlideViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            vm.ImageUrl = SaveFile(vm.Image, AppConfig.SlideImagesPath);
            vm.OrderNumber = DataContext.GetRepository<Slide>().GetAll().Count();

            CreateModel<Slide, SlideViewModel>(vm);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var vm = GetViewModel<Slide, SlideViewModel>(id);

            if(vm == null)
            {
                return RedirectToAction("Index");
            }

            ToView(vm);

            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(SlideViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var slide = DataContext.GetRepository<Slide>().GetById(vm.Id);

            if(slide != null)
            {
                slide.Title = vm.Title;

                if(vm.Image != null)
                {
                    slide.ImageUrl = SaveFile(vm.Image, AppConfig.SlideImagesPath);
                }

                DataContext.GetRepository<Slide>().Update(slide);
                DataContext.Save();
            }

            return RedirectToAction("Index");
        }

        [HttpPut]
        public ActionResult Hide(int id)
        {
            var vm = GetViewModel<Slide, SlideViewModel>(id);
            
            if(vm != null)
            {
                vm.IsHidden = !vm.IsHidden;
                UpdateModel<Slide, SlideViewModel>(vm, id);

                ToView(vm);

                return PartialView("_SlideRow", vm);
            }            

            return new EmptyResult();
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            DeleteModel<Slide>(id);

            var repo = DataContext.GetRepository<Slide>();

            var slides = repo.GetAll().OrderBy(i => i.OrderNumber).ToList();

            for(int i = 0; i < slides.Count; i++)
            {
                var slide = slides[i];
                slide.OrderNumber = i;
                repo.Update(slide);
            }

            DataContext.Save();

            return new EmptyResult();
        }

        [HttpPut]
        public ActionResult Up(int id)
        {
            var slides = DataContext.GetRepository<Slide>().GetAll().OrderBy(s => s.OrderNumber).ToList();

            var current = slides.FirstOrDefault(i => i.Id == id);

            if(current != null && current.OrderNumber != 0)
            {
                var last = slides[current.OrderNumber - 1];
                last.OrderNumber = current.OrderNumber;
                current.OrderNumber = current.OrderNumber - 1;

                DataContext.GetRepository<Slide>().Update(last);
                DataContext.GetRepository<Slide>().Update(current);
                DataContext.Save();
            }

            var result = GetSlideViewModels();
            return PartialView("_SlideList", result);
        }

        [HttpPut]
        public ActionResult Down(int id)
        {
            var slides = DataContext.GetRepository<Slide>().GetAll().OrderBy(s => s.OrderNumber).ToList();

            var current = slides.FirstOrDefault(i => i.Id == id);

            if (current != null && current.OrderNumber < slides.Count - 1)
            {
                var next = slides[current.OrderNumber + 1];
                next.OrderNumber = current.OrderNumber;
                current.OrderNumber = current.OrderNumber + 1;

                DataContext.GetRepository<Slide>().Update(next);
                DataContext.GetRepository<Slide>().Update(current);
                DataContext.Save();
            }

            var result = GetSlideViewModels();
            return PartialView("_SlideList", result);
        }

        protected SlideViewModel ToView(SlideViewModel vm)
        {
            if(vm == null)
            {
                return null;
            }

            vm.ImageUrl = GetFileLink(AppConfig.SlideImagesPath, vm.ImageUrl);

            return vm;
        }
        protected List<SlideViewModel> GetSlideViewModels()
        {
            var result = GetViewModelCollection<Slide, SlideViewModel>().OrderBy(s => s.OrderNumber).Select(ToView).ToList();
            if (result.Count > 0)
            {
                var first = result.FirstOrDefault();
                var last = result.LastOrDefault();
                if (first != null)
                {
                    first.IsFirst = true;
                }
                if (last != null)
                {
                    last.IsLast = true;
                }
            }
            return result;
        }
    }
}

Mettal/Controllers/TableController.cs
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using Mettal.Models.Entities;
using Mettal.Models.ViewModels;

namespace Mettal.Controllers
{
    [Authorize(Roles = "admin")]
    public class TableController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var vm = new TableView
            {
                Tables = GetViewModelCollection<Table, TableViewModel>().ToList()
            };

            return View(vm);
        }

        [HttpGet]
        public ActionResult Update(int? id = null)
        {
            if (id == null)
            {
                return View("Update", GetNewTable());
            }

            var vm = GetViewModel<Table, TableViewModel>(id);

            return View("Update", vm);
        }

        [HttpPost]
        public ActionResult Update(TableViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("Update", vm);
            }

            if (vm.Id > 0)
            {
                UpdateModel<Table, TableViewModel>(vm, vm.Id);
            }
            else
            {
                CreateModel<Table, TableViewModel>(vm);
            }

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            DeleteModel<Table>(id);

            return new EmptyResult();
        }

        protected TableViewModel GetNewTable()
        {
            var vm = new TableViewModel();
            var properties = vm
                .GetType()
                .GetProperties()
                .Where(p => p.GetCustomAttribute(typeof(DisplayNameAttribute)) != null);

            foreach (PropertyInfo property in properties)
            {
                var attr = property.GetCustomAttribute(typeof(DisplayNameAttribute)) as DisplayNameAttribute;

                if (attr != null)
                {
                    property.SetValue(vm, attr.DisplayName);
                }
            }

            return vm;
        }
    }
}

Mettal/Views/Shared/_Categories.cshtml
@model IEnumerable<Mettal.Models.ViewModels.CategoryViewModel>

<div class="categories" id="categories-section">
    <div class="container">
        <div class="text-center">
            <h1>Наша продукция</h1>
        </div>
        <div class="row items">
            @foreach (var item in Model)
            {
                <div class="col-md-4" id="item-@item.Id">
                    <div class="item" style="background-image: url('@item.ImageViewLink')">
                        <div class="text-wrapper text-center">
                            @Html.ActionLink("Позиции", "Positions", "Product", new { id = item.Id }, new { @class = "" })
                            @if (!String.IsNullOrEmpty(item.HtmlContent)) {
                                @Html.ActionLink("Подробнее", "Details", "Category", new { id = item.Id }, new { @class = "" })
                            }
                        </div>
                    </div>
                    <p class="name">@Html.ActionLink(item.DisplayName, "Positions", "Product", new { id = item.Id }, new { @class = "" })</p>
                    @if (ViewBag.IsAdmin)
                    {
                        <div class="controls">
                            @Html.ActionLink("Изменить", "Update", "Category", new { id = item.Id }, new { })
                            |
                            @Ajax.ActionLink("Удалить", "Delete", "Category", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "item-" + item.Id, InsertionMode = InsertionMode.ReplaceWith, HttpMethod = "DELETE", Confirm = "Вы действительно хотите удалить?" })
                            |
                            @Html.ActionLink("Новая позиция", "Create", "Product", new { id = item.Id }, new { })
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

Mettal/Views/Shared/_HtmlEditor.cshtml
@model Mettal.Models.ViewModels.HtmlEditorViewModel

<div class="html-editor">
    <script src="/ckeditor/ckeditor.js"></script>
    <div class="html-editor-inner">
        <textarea id="html-editor-@Model.PropertyName" name="@Model.PropertyName" class="form-control html-editor">@Model.HtmlContent</textarea>
    </div>
    <script>
        CKEDITOR.replace('html-editor-@Model.PropertyName', {
            height: '400px'
        });
    </script>
</div>

Mettal/Views/Shared/_Layout.cshtml
@using Mettal.Models.Business
@using Mettal.Models.ViewModels
@{
    AppSettings settings = (AppSettings)ViewBag.Settings;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="http://allfont.ru/allfont.css?fonts=university-cyrillic" rel="stylesheet" type="text/css" />
    <link href="http://allfont.ru/allfont.css?fonts=compact" rel="stylesheet" type="text/css" />
    <link href="http://allfont.ru/allfont.css?fonts=hair-2" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">
                    <img src="/Images/logo.png" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Продукция", "Index", "Category")</li>
                    @*<li>@Html.ActionLink("Услуги", "About", "Home")</li>*@
                    @*<li>@Html.ActionLink("Вопрос-ответ", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Справочник", "Index", "Manual")</li>
                    <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                    @if ((bool)ViewBag.IsAdmin)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Администратор <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Таблицы", "Index", "Table")</li>
                                <li>@Html.ActionLink("Категории", "Edit", "Category")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Госты", "Index", "Gost")</li>
                                <li>@Html.ActionLink("Марки", "Index", "Mark")</li>
                                <li>@Html.ActionLink("Страны", "Index", "Country")</li>
                                <li>@Html.ActionLink("Назначения", "Index", "Target")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Справочник", "Categories", "Manual")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Слайдер", "Index", "Slider")</li>
                                <li>@Html.ActionLink("Настройки", "Index", "Settings")</li>
                            </ul>
                        </li>
                    }
                    @Html.Partial("_LoginPartial")
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!string.IsNullOrEmpty(settings.Phone1))
                    {
                        <li class="phone">
                            @settings.Phone1
                            
                            @if (!string.IsNullOrEmpty(settings.Phone2))
                            {
                                <br />@settings.Phone2
                            }
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">

        @RenderBody()

        <footer>

            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h3>Карта сайта</h3>
                        <ul>
                            <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                            <li>@Html.ActionLink("Продукция", "Index", "Category")</li>
                            @*<li>@Html.ActionLink("Услуги", "About", "Home")</li>*@
                            @*<li>@Html.ActionLink("Вопрос-ответ", "About", "Home")</li>*@
                            <li>@Html.ActionLink("Справочник", "Index", "Manual")</li>
                            <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>Контакты</h3>
                        <ul>
                            @if (!string.IsNullOrEmpty(settings.Phone1))
                            {
                                <li><a>@settings.Phone1</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.Phone2))
                            {
                                <li><a>@settings.Phone2</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.Phone3))
                            {
                                <li><a>@settings.Phone3</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.Email1))
                            {
                                <li><a>@settings.Email1</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.Email2))
                            {
                                <li><a>@settings.Email2</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.Email3))
                            {
                                <li><a>@settings.Email3</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.AddressOffice))
                            {
                                <li><a>Офис: @settings.AddressOffice</a></li>
                            }
                            @if (!string.IsNullOrEmpty(settings.AddressSklad))
                            {
                                <li><a>Склад: @settings.AddressSklad</a></li>
                            }
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>Заказать звонок</h3>
                        @Html.Partial("~/Views/Callback/_CallForm.cshtml", new CallbackViewModel())
                    </div>
                </div>
                <div class="text-center">
                    <p class="copyright">&copy; 2000 - @DateTime.Now.Year</p>
                </div>
            </div>

        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>

Mettal/Views/Shared/_Map.cshtml
@model Mettal.Models.Business.AppSettings

<div class="maps">
    <div class="container">
        <div class="text-center">
            <h1>Схема проезда</h1>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div>
                    <h2 class="text-center">Наш офис</h2>
                    <p class="text-center">@Model.AddressOffice</p>
                    <div id="map-office" class="map">
                        <iframe src="@Model.OfficeMapUrl" width="100%" height="450" frameborder="0" style="border: 0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    <h2 class="text-center">Наш склад</h2>
                    <p class="text-center">@Model.AddressSklad</p>
                    <div id="map-sklad" class="map">
                        <iframe src="@Model.SkladMapUrl" width="100%" height="450" frameborder="0" style="border: 0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Mettal/Views/Shared/_Slider.cshtml
@using Mettal.Models.ViewModels
@model IEnumerable<Mettal.Models.ViewModels.SlideViewModel>
@{
    int index = 0;
}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    @*<ol class="carousel-indicators">
            @foreach (var slide in Model)
            {
                <li data-target="#carousel-example-generic" data-slide-to="@index" class='@(index++ == 0 ? "active" : "")'></li>
            }
        </ol>*@

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        @{
            index = 0;
        }
        @foreach (var slide in Model)
        {
            <div class='item @(index++ == 0 ? "active" : "")'>
                <img src="@slide.ImageUrl" alt="@slide.Title">
                @*<div class="carousel-caption">
                        @slide.Title
                    </div>*@
            </div>
        }
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>

    <div class="text-center goto-products">
        <h3><a href="#categories-section"><span>Перейти к продукции <br /> <span class="glyphicon glyphicon-chevron-down"></span></span></a></h3>
    </div>
</div>

<div class="company-name">
    <h1>БАТИСМЕТ</h1>
    <h3>Нержавейка, спецметалл.</h3>
</div>

<div class="callback-head">
    <h3>Заказать звонок</h3>
    @Html.Partial("~/Views/Callback/_CallForm.cshtml", new CallbackViewModel())
</div>